# Generated by Django 2.2.5 on 2019-10-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('scrum_master', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrumMaster',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('PBIID', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('user_story', models.CharField(max_length=100)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
