# Generated by Django 2.2.5 on 2019-10-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('scrumMaster', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrumMaster',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('projectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBacklogItem',
            fields=[
                ('pbiId', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('userStory', models.TextField()),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('projectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wolfpack.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
