# Generated by Django 2.2.5 on 2019-10-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklogitem',
            old_name='pbiId',
            new_name='id',
        ),
    ]
