# Generated by Django 2.2.5 on 2019-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpack', '0002_auto_20191022_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='user_story',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
