# Generated by Django 2.2.5 on 2019-10-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpack', '0002_auto_20191022_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='projectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wolfpack.Project'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wolfpack.Project'),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wolfpack.Project'),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scrummaster',
            name='projectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wolfpack.Project'),
        ),
        migrations.AlterField(
            model_name='scrummaster',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
