# Generated by Django 2.2.5 on 2019-10-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpack', '0003_auto_20191022_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbi',
            old_name='PBIID',
            new_name='ID',
        ),
    ]
